Fixed change_passwd_on_login option of user module, because it did not work as expected
IBM/ansible-power-aix pull request #43
Opened 2020-09-28 19:30 UTC by sboldt1978

change_passwd_on_login option of user module did not work as expected: If "false" you had to change the password at next login, if "true" you didn't.
Background: The "-c" option of chpasswd clears all password flags (such as "change at next login"). Therefore this needs to be set only if change_passwd_on_login is set to "false"

2020-10-01 10:38 UTC, kavanabhat commented on plugins/modules/user.py
> +        module.fail_json(msg=msg, rc=pass_rc, stdout=pass_out, stderr=pass_err)
pass_rc, pass_out or pass_err is not set at this point

2020-10-01 10:44 UTC, kavanabhat commented on plugins/modules/user.py
> +        cmd = "echo \'{user}:{cleartext_passwd}\' | chpasswd".format(user=name, password=cleartext_passwd)
"cleartext_passwd=cleartext_passwd" should be used in the format statement and not "passwd=cleartext_passwd".

2020-10-01 10:44 UTC, kavanabhat commented on plugins/modules/user.py
> +        cmd = "echo \'{user}:{cleartext_passwd}\' | chpasswd -c".format(user=name, password=cleartext_passwd)
Same as above

2020-10-01 10:45 UTC, kavanabhat commented on plugins/modules/user.py
> +    description: Specifies and unencrypted cleartext string for the password to create or change the password.
Fix the typo in the description for cleartext_password "Specifies and unencrypted" as "Specifies an unencrypted"

2020-10-01 10:52 UTC, kavanabhat requested changes
Please fix the mentioned comments and test the module for modification of password using cleartext_password option.

2020-10-13 21:54 UTC, closed without merging

2020-10-13 21:55 UTC, sboldt1978 commented
Included code that was not meant to be included in pull request